### ISSUE TITLE
RFE: Support iteration through the Exports object

### ISSUE THREAD

**Issue by FGasper** [wasmerio/wasmer-python#535]
### Motivation

https://github.com/miracle2k/wasmbind (a port of AssemblyScript’s loader to Python) depends on the ability to iterate through the exports. The 1.0.0 release of wasmer-python, though, seems to lack this ability.

It looks like it _used_ to work to JSON-ify the Exports object, but that’s no longer the case, as a result of which wasmbind is now completely broken (even if one _does_ provide the missing `env.abort` that almost every AssemblyScript program requires).

### Proposed solution

Make the Exports object an iterator so that calling Python code can easily list all of the exports.

If I may, a very useful demonstration would be to use wasmer-python to implement the C API’s reflect.c demo.

Thank you!

**Comment by Hywan** [comment]
Hello,

`Module.exports` returns a Python list of `ExportType`, so it is iterable.
`Module.imports` returns a Python list of `ImportType`, so it is iterable.
`Instance.exports` returns an  `Exports` object, which implement partially the Sequence Protocol (partially because it is a read-only object). But it doesn't implement the Iterator Protocol, that's true.
